### PR TITLE
fixed the structure of the text in one place

### PR DESCRIPTION
**Pull request by hemmefelix**
Changed the position of a comma.

### CODE REVIEW

**Comment by drjwbaker** [comment]
Hi @hemmefelix. Thanks for your contribution. Not merging for now as I think this change would introduce some inconsistency: many LC lessons used oxford commas for lists (I write with them, and many of the lessons were written by me in the first case, hence the use here).

As far as I can see, we don't have a proper style guide, this https://carpentries.github.io/lesson-example/ is the nearest we have. 

@libcce @rgaiacs: can we push this up the Carpentries chain please. Why don't we have a style guide for editing our lessons? (like a scholarly journal would)

**Comment by libcce** [comment]
Hi @drjwbaker it is very new but here is the style guide https://docs.carpentries.org/topic_folders/communications/style-guide.html?highlight=style%20guide. There is a section on Commas and Oxford Comma.

**Comment by hemmefelix** [comment]
This is a helpful resource. Thanks @libcce.

**Comment by drjwbaker** [comment]
Awesome style guide @weaverbel.

@hemmefelix: having looked at the guide, what do you think? I think the change should be from..

> Then test each other on the answers. If you want to check your logic, use [regex101](https://regex101.com/), [myregexp](http://myregexp.com/), or [regex pal](http://www.regexpal.com/) [regexper.com](http://regexper.com/): the first three help you see what text your regular expression will match, the latter visualises the workflow of a regular expression.

..to..

Then test each other on the answers. If you want to check your logic use [regex101](https://regex101.com/), [myregexp](http://myregexp.com/) or [regex pal](http://www.regexpal.com/) [regexper.com](http://regexper.com/): the first three help you see what text your regular expression will match, the latter visualises the workflow of a regular expression.

(so, we lose two commas).

Agreed?

**Comment by hemmefelix** [comment]
@drjwbaker As I am not a native English speaker, I have full confidence in this proposal.

**Comment by drjwbaker** [comment]
@hemmefelix Okay!

**Pull request merged**
