### PR TITLE
Update reference.md

### PR DESCRIPTION
**Pull request by mlandryacenet**
It should read "Putting this either side of a word..." on line 15.

### CODE REVIEW

**Comment by mlandryacenet** [comment]
Ah, I'm thinking 2 backslashes were used in the Reference document, instead of 1, because 1 backslash.com is not visible in my PR comment.

**Comment by sharilaster** [comment]
Yes @mlandryacenet that's correct -- the backslash needs to be backslashed so it shows up when the markup is parsed. And, thanks for catching that missed word! Do you mind updating your PR so that it only includes the text correction? Once you've done so I can merge.

**Comment by mlandryacenet** [comment]
I'm unsure if I updated the PR correctly - I'm still very new to GitHub. If I didn't do it correctly, I can delete and resubmit. Thanks for your help!

**Comment by sharilaster** [comment]
No worries, I am not at all an expert with GitHub either!!! It looks like this version would only edit the backslash, rather than only editing the missing word. So feel free to edit again, or if you prefer to just submit a new PR, that also works for me!

**Comment by sharilaster** [comment]
Actually -- I just took a second look and it is correct!! Sorry about that. I will merge.

**Comment by sharilaster** [comment]
Thank you @mlandryacenet for your contribution!!

**Pull request merged**
