### PR TITLE
Update guide.md

### PR DESCRIPTION
**Pull request by drjwbaker**
Add note on sticky colour choice for colour blind/deficient instructors/helpers.

### CODE REVIEW

**Comment by libcce** [comment]
Might be a good PR for some of our new Maintainers @antonangelo @ppival @sharilaster This is a great addition BTW!

**Comment by libcce** [comment]
Oops turns out this was a merge conflict @antonangelo @ppival @sharilaster so @ccronje is going to try to troubleshoot 😃

**Comment by ccronje** [comment]
Thanks @drjwbaker @libcce - successfully merged.

**Comment by drjwbaker** [comment]
Ta. And apologies for causing the conflict!

**Pull request merged**
