### PR TITLE
Update 01-regular-expressions.md

### PR DESCRIPTION
**Pull request by kevintfrench**
Please delete this line and the text below before submitting your contribution.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.

---

### CODE REVIEW

**Comment by kevintfrench** [comment]
I found the link is not https but http so it may be worth finding another example though this is an excellent one.

**Comment by sharilaster** [comment]
Hi @kevintfrench, it looks like this is responding to issue #210, is that correct? I tagged that issue as a Good First Issue but based on your note about the http link, maybe it is a bit more complicated than I first thought! It looks like Bohyun may no longer be updating/maintaining her blog, which is why there isn't a version currently available in https. 

I think a good strategy may be to link to the original published version, which is here: https://acrl.ala.org/techconnect/post/fear-no-longer-regular-expressions/ and then we could continue the discussion in #210 to look for another similar resource. Does that work for you?

**Comment by kevintfrench** [comment]
I see what you mean, @sharilaster though there are updates in other sections of library hat, there doesn't seem to be anything in the blog which, I'm sad to see, is also the case for ACRL Tech Connect.  I switched out the link in favor of the one you found.

**Comment by sharilaster** [comment]
Thank you @kevintfrench!

**Pull request merged**
